spring:
  datasource:
    url: jdbc:mysql://j8c101.p.ssafy.io:3306/chorongddara?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 977124759021-pe1aj9ot5g3li9bm9imbspa1it69kns3.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://j8c101.p.ssafy.io:8080/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          kakao:
            client-id: 31a020d01fc6ab8f9c9cc9064e7b451b
            client-secret: XEnTXhQlZzcyc9n2XZdPfBX1Aio0C9if
            redirect-uri: "http://j8c101.p.ssafy.io:8080/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  jwt:
    accessSecret: accesschorongddarachorongddarachorongddarachorongddarachorongddara
    refreshSecret: refreshchorongddarachorongddarachorongddarachorongddarachorongddara
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 500MB

file:
  upload:
    path: /home/ubuntu/chorongddara/upload/

logging:
  pattern:
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  file:
    name: ./log/logs.log
  level:
    root: info
    com.ssafy.chorongddara: Debug

redis:
  host: j8c101.p.ssafy.io
  port: 6379
#cloud:
#  aws:
#    s3:
#      bucket: ssafy.common.gaza
#    credentials:
#      access-key:
#      secret-key:
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    directory: /gaza
#
#session:
#  store-type:redis
